Docstring and codestyle
Capwell/ProninTeamBack pull request #17
Opened 2022-12-14 12:53 UTC by anywindblows

- Placed the fields in order of priority in the model
- Added documentation according to https://docs.djangoproject.com/en/4.1/ref/contrib/admin/admindocs/
- Added __str__ representation of models
- Added gettext_lazy
- Additional params for displaying models in the admin panel

2022-12-15 16:24 UTC, anywindblows reviewed
Resolve conflicts

2023-02-16 17:27 UTC, Capwell requested changes

2023-02-16 17:27 UTC, Capwell commented on proninteam/cases/admin.py
> +admin.site.register(Case, CaseAdmin)
возможно, стоит использовать @admin.register  ?

2023-02-16 17:27 UTC, Capwell commented on proninteam/cases/models.py
> +        verbose_name=_('Название'),
с прописной

2023-02-16 17:27 UTC, Capwell commented on proninteam/cases/models.py
> +        verbose_name=_('Цвет'),
с прописной

2023-02-16 17:27 UTC, Capwell commented on proninteam/cases/models.py
> +        verbose_name=_('Лого'),
с прописной

2023-02-16 17:27 UTC, Capwell commented on proninteam/cases/models.py
> +        verbose_name=_('Описание кейса'),
с прописной

2023-02-16 17:27 UTC, Capwell commented on proninteam/cases/models.py
> +        verbose_name=_('Ссылка'),
с прописной

2023-02-16 17:27 UTC, Capwell commented on proninteam/cases/models.py
> +        verbose_name=_('Видимый'),
с прописной

2023-02-16 17:27 UTC, Capwell commented on proninteam/cases/models.py
> +    def __str__(self) -> str:
тайпихинты бессмысленны

2023-02-16 17:27 UTC, Capwell commented on proninteam/offers/models.py
> +        verbose_name=_('Имя'),
с прописной (далее везде)

2023-04-07 11:25 UTC, closed without merging